addons:
  apt:
    packages:
      - time
language: node_js
node_js:
- "5.0"
env:
  - chromeBinaryPath=/home/travis/build/samccone/drool/chrome-linux/chrome
before_install:
- sudo apt-get install -y brotli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip
script:
- make all
